package TestJava.Test149;

public class Main {
    public static void main(String[] args) {
        System.out.println("=== Java Native Interface (JNI) Basics ===\n");

        System.out.println("JNI allows Java to call native code written in C or C++!");
        System.out.println("This is used for high-performance math (like AI/TensorFlow), hardware drivers, or interacting with the OS.\n");

        System.out.println("--- Step 1: Declare the Native Method ---");
        System.out.println("public class NativeMath {");
        System.out.println("    // The 'native' keyword tells the JVM that the implementation is in C/C++");
        System.out.println("    public native long fastMultiply(long a, long b);");
        System.out.println("}");
        
        System.out.println("\n--- Step 2: Load the Native Library ---");
        System.out.println("static {");
        System.out.println("    // This loads a file named 'mathlib.dll' (Windows) or 'libmathlib.so' (Linux)");
        System.out.println("    System.loadLibrary(\"mathlib\");");
        System.out.println("}");

        System.out.println("\n--- Step 3: Implement in C/C++ (via 'javac -h') ---");
        String cCode = """
            #include "NativeMath.h"
            
            // This horrific method signature is generated by Java tools
            JNIEXPORT jlong JNICALL Java_NativeMath_fastMultiply(JNIEnv *env, jobject obj, jlong a, jlong b) {
                // Here we write raw, high-speed C code!
                return a * b; // In real life, this might use SIMD vector instructions!
            }
            """;
        System.out.println(cCode);
        
        System.out.println("\nNote on Java 22+: Project Panama (Foreign Function & Memory API) is replacing JNI!");
        System.out.println("Panama allows Java to call C libraries directly without needing middleman JNI C-code!");
    }
}
