server.port=8084

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-consumers
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=5
spring.kafka.listener.concurrency=3
spring.kafka.listener.ack-mode=manual
spring.kafka.template.default-topic=order-events

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.server.port=8084
