# Spring Application Name
spring.application.name=tracing-demo-service

# Zipkin Server URL
spring.zipkin.base-url=http://localhost:9411

# Sampling probability (1.0 = 100% of requests are traced)
spring.sleuth.sampler.probability=1.0

# Logging pattern to include TraceId and SpanId
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
