apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee-app
        image: employee-service:v1
        ports:
        - containerPort: 8080
