server.port=9292
spring.application.name=CONFIG-SERVER

# Where to find the configuration files
# In a real app, this would be a GitHub URL
# For this test, we use 'native' which means local filesystem
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:/home/vikasp/Project/DesginePattern/Microserservice-Springboot/test8/config-repo
