server:
  port: 8102
spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:h2:mem:driverdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
