# App Basic Info
app.name=Spring Boot Learning App
app.version=1.0.0
app.description=A simple app to learn external configuration.

# Grouped Properties (for @ConfigurationProperties)
mail.hostname=smtp.gmail.com
mail.port=587
mail.from=admin@example.com
