spring.application.name=swagger-aggregator
# Configuration to pull OpenAPI docs from other services
springdoc.swagger-ui.urls[0].name=Employee-Service
springdoc.swagger-ui.urls[0].url=http://localhost:8081/v3/api-docs
springdoc.swagger-ui.urls[1].name=Payment-Service
springdoc.swagger-ui.urls[1].url=http://localhost:8082/v3/api-docs
